spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  environment: development
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false

---
spring:
  profiles: docker
  instance:
    hostname: eureka

eureka:
  environment: docker
