server:
  port: 9000

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Development/config

eureka:
  environment: development
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: /opt/config

eureka:
  environment: docker
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
