server:
  port: 9000

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/perch24/sdd-config.git

eureka:
  environment: development
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker

eureka:
  environment: docker
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
